#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

current_branch=$(git rev-parse --abbrev-ref HEAD)

if [ "$current_branch" = "main" ]; then
  echo -e "\033[0;31mCommit directly to the 'main' branch is not allowed. Please, create a new branch...\033[0m"
  exit 1
fi

changed_files=$(git diff --cached --name-only)

if echo "$changed_files" | grep --quiet "^src/"; then
  npm run lint:src
fi